### ISSUE TITLE
Parser gives error when reading `.pgn` files

### ISSUE THREAD

**Issue by Montekkundan** [hrushikeshrv/chessengine#2]
When running `play.py`

` b.play()` function gives this error.

![image](https://user-images.githubusercontent.com/87750128/192708216-498472ec-8a15-40ef-ba01-9d7ccafa3b93.png)

Even after running `python -m chessengine.play` I get an error

![image](https://user-images.githubusercontent.com/87750128/192708239-7eb83135-c898-43e8-95e0-efc4ee5417c5.png)

**Comment by hrushikeshrv** [comment]
Thanks for this, can you please check the contents of the folder where the PGN files are stored? It should be in `Users/montekkundan/Documents/GitHub/chessengine/chessengine/openings/`. Ordinarily there should only be 3 `.pgn` files, but it seems like there are a few others and/or a directory.

**Comment by Montekkundan** [comment]
Contents in openings folder:


<img width="340" alt="image" src="https://user-images.githubusercontent.com/87750128/192715823-70519207-af87-4950-b2d5-1ba76f06e99e.png">

**Comment by zzril** [comment]
There seems to be an encoding issue with the PGN files.
According to [Wiki](https://en.wikipedia.org/wiki/Portable_Game_Notation), PGN files must be ASCII-encoded, so I think the best solution is to just ignore any non-ASCII characters in the PGN.
I fixed it by passing the "errors='replace'" parameter to the "open" functions. (See my Pull Request.)

**Comment by hrushikeshrv** [comment]
@zzril Thanks for the PR. It does seem like the parser is encountering an invalid byte, but the problem is that it shouldn't be running into this bug at all. The PGN files I have included with the package don't have any invalid bytes, and I am able to read them all locally. Right now I'm considering if its because of a difference in python versions or related to the installation environment somehow, because I can't reproduce this bug on my machine.
Are you running into this bug as well? If so, did adding the `errors="replace"` parameter fix it for you?
If it keeps persisting, I think we should try your solution 👍🏻 

Thanks again :)

**Comment by Montekkundan** [comment]
@hrushikeshrv it works!

Thanks @zzril, after adding `errors='replace'` to `parser.py` it worked!

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/87750128/192820716-1a655201-7040-43e9-a318-0b0a8b857ff9.png">

**Comment by zzril** [comment]
@hrushikeshrv The "Modern.pgn" and "Modern3Nc3-d6.pgn" had invalid bytes. (For the "Modern.pgn", the problem was the `í` (not `i`) used in `[Site Lechería]` in some tag.)  
The file seems to use `Windows-1252`-encoding, where this letter is encoded as an `\xed` byte.  
So, yeah, probably depends on the installation environment / operating system whether Python reads that correctly or not. On my Linux machine, it didn't. ^^

Glad I could help!

**Comment by hrushikeshrv** [comment]
@zzril that makes sense. Thanks for your help!
